//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://recuperoinformativa.wsdl.fse.ini.finanze.it", ConfigurationName="ServiceReference1.recuperoInformativaPT")]
    public interface recuperoInformativaPT
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://recuperoinformativa.wsdl.fse.ini.finanze.it/RecuperoInformativa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.recuperoInformativaResponse> recuperoInformativaAsync(ServiceReference1.recuperoInformativaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://recuperoinformativarichiesta.xsd.fse.ini.finanze.it")]
    public partial class RecuperoInformativaRichiesta
    {
        
        private string identificativoUtenteField;
        
        private string pinCodeField;
        
        private string identificativoOrganizzazioneField;
        
        private string strutturaUtenteField;
        
        private string ruoloUtenteField;
        
        private string tipoAttivitaField;
        
        private string identificativoInformativaField;
        
        private opzioniType[] opzioniRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdentificativoUtente
        {
            get
            {
                return this.identificativoUtenteField;
            }
            set
            {
                this.identificativoUtenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string pinCode
        {
            get
            {
                return this.pinCodeField;
            }
            set
            {
                this.pinCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdentificativoOrganizzazione
        {
            get
            {
                return this.identificativoOrganizzazioneField;
            }
            set
            {
                this.identificativoOrganizzazioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StrutturaUtente
        {
            get
            {
                return this.strutturaUtenteField;
            }
            set
            {
                this.strutturaUtenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RuoloUtente
        {
            get
            {
                return this.ruoloUtenteField;
            }
            set
            {
                this.ruoloUtenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TipoAttivita
        {
            get
            {
                return this.tipoAttivitaField;
            }
            set
            {
                this.tipoAttivitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IdentificativoInformativa
        {
            get
            {
                return this.identificativoInformativaField;
            }
            set
            {
                this.identificativoInformativaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OpzioniRequest", Order=7)]
        public opzioniType[] OpzioniRequest
        {
            get
            {
                return this.opzioniRequestField;
            }
            set
            {
                this.opzioniRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tipodatirecuperoinformativa.xsd.fse.ini.finanze.it")]
    public partial class opzioniType
    {
        
        private string chiaveField;
        
        private string valoreField;
        
        private string tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string chiave
        {
            get
            {
                return this.chiaveField;
            }
            set
            {
                this.chiaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string valore
        {
            get
            {
                return this.valoreField;
            }
            set
            {
                this.valoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tipodatirecuperoinformativa.xsd.fse.ini.finanze.it")]
    public partial class erroreType
    {
        
        private string codEsitoField;
        
        private string esitoField;
        
        private string tipoErroreField;
        
        private string fonteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codEsito
        {
            get
            {
                return this.codEsitoField;
            }
            set
            {
                this.codEsitoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string esito
        {
            get
            {
                return this.esitoField;
            }
            set
            {
                this.esitoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string tipoErrore
        {
            get
            {
                return this.tipoErroreField;
            }
            set
            {
                this.tipoErroreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string fonte
        {
            get
            {
                return this.fonteField;
            }
            set
            {
                this.fonteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://recuperoinformativaricevuta.xsd.fse.ini.finanze.it")]
    public partial class RecuperoInformativaRicevuta
    {
        
        private string esitoField;
        
        private erroreType[] elencoErroriField;
        
        private string identificativoInformativaField;
        
        private byte[] informativaField;
        
        private string tipoMimeInformativaField;
        
        private byte[] modulisticaField;
        
        private string tipoMimeModulisticaField;
        
        private opzioniType[] opzioniResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Esito
        {
            get
            {
                return this.esitoField;
            }
            set
            {
                this.esitoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Errore", Namespace="http://tipodatirecuperoinformativa.xsd.fse.ini.finanze.it", IsNullable=false)]
        public erroreType[] ElencoErrori
        {
            get
            {
                return this.elencoErroriField;
            }
            set
            {
                this.elencoErroriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdentificativoInformativa
        {
            get
            {
                return this.identificativoInformativaField;
            }
            set
            {
                this.identificativoInformativaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] Informativa
        {
            get
            {
                return this.informativaField;
            }
            set
            {
                this.informativaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TipoMimeInformativa
        {
            get
            {
                return this.tipoMimeInformativaField;
            }
            set
            {
                this.tipoMimeInformativaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=5)]
        public byte[] Modulistica
        {
            get
            {
                return this.modulisticaField;
            }
            set
            {
                this.modulisticaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TipoMimeModulistica
        {
            get
            {
                return this.tipoMimeModulisticaField;
            }
            set
            {
                this.tipoMimeModulisticaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OpzioniResponse", Order=7)]
        public opzioniType[] OpzioniResponse
        {
            get
            {
                return this.opzioniResponseField;
            }
            set
            {
                this.opzioniResponseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recuperoInformativaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recuperoinformativarichiesta.xsd.fse.ini.finanze.it", Order=0)]
        public ServiceReference1.RecuperoInformativaRichiesta RecuperoInformativaRichiesta;
        
        public recuperoInformativaRequest()
        {
        }
        
        public recuperoInformativaRequest(ServiceReference1.RecuperoInformativaRichiesta RecuperoInformativaRichiesta)
        {
            this.RecuperoInformativaRichiesta = RecuperoInformativaRichiesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recuperoInformativaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://recuperoinformativaricevuta.xsd.fse.ini.finanze.it", Order=0)]
        public ServiceReference1.RecuperoInformativaRicevuta RecuperoInformativaRicevuta;
        
        public recuperoInformativaResponse()
        {
        }
        
        public recuperoInformativaResponse(ServiceReference1.RecuperoInformativaRicevuta RecuperoInformativaRicevuta)
        {
            this.RecuperoInformativaRicevuta = RecuperoInformativaRicevuta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface recuperoInformativaPTChannel : ServiceReference1.recuperoInformativaPT, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class recuperoInformativaPTClient : System.ServiceModel.ClientBase<ServiceReference1.recuperoInformativaPT>, ServiceReference1.recuperoInformativaPT
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public recuperoInformativaPTClient() : 
                base(recuperoInformativaPTClient.GetDefaultBinding(), recuperoInformativaPTClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.fseRecuperoInformativa.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public recuperoInformativaPTClient(EndpointConfiguration endpointConfiguration) : 
                base(recuperoInformativaPTClient.GetBindingForEndpoint(endpointConfiguration), recuperoInformativaPTClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public recuperoInformativaPTClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(recuperoInformativaPTClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public recuperoInformativaPTClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(recuperoInformativaPTClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public recuperoInformativaPTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.recuperoInformativaResponse> ServiceReference1.recuperoInformativaPT.recuperoInformativaAsync(ServiceReference1.recuperoInformativaRequest request)
        {
            return base.Channel.recuperoInformativaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.recuperoInformativaResponse> recuperoInformativaAsync(ServiceReference1.RecuperoInformativaRichiesta RecuperoInformativaRichiesta)
        {
            ServiceReference1.recuperoInformativaRequest inValue = new ServiceReference1.recuperoInformativaRequest();
            inValue.RecuperoInformativaRichiesta = RecuperoInformativaRichiesta;
            return ((ServiceReference1.recuperoInformativaPT)(this)).recuperoInformativaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.fseRecuperoInformativa))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.fseRecuperoInformativa))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:9080/FseInsServicesWeb/services/fseRecuperoInformativa");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return recuperoInformativaPTClient.GetBindingForEndpoint(EndpointConfiguration.fseRecuperoInformativa);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return recuperoInformativaPTClient.GetEndpointAddress(EndpointConfiguration.fseRecuperoInformativa);
        }
        
        public enum EndpointConfiguration
        {
            
            fseRecuperoInformativa,
        }
    }
}
